name: harmony
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3
  - h5py
  - numpy
  - tqdm
  - jupyter
  - pandas
  - pytorch
  - cpuonly
  - pytorch-lightning
  - pytest
  - pytest-cov
