name: harmony
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3
  - h5py
  - numpy=1.19
  - tqdm
  - jupyter
  - pandas=1.1.1
  - pytorch
  - cpuonly
  - pytorch-lightning
  - pytest
  - pytest-cov
